{
 "title": "Api",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Api Request Count/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(ds_api_request_count_total{}[1m]))"
    }
   ]
  },
  {
   "title": "Api Response Time/5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(ds_api_response_time_milliseconds{}[5m])"
    }
   ]
  },
  {
   "title": "Api Response Count/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(ds_api_response_count_total{}[1m]))"
    }
   ]
  },
  {
   "title": "Api Abnormal Response Count/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(ds_api_response_count_total{code=\"3xx\"}[1m]))"
    },
    {
     "expr": "sum(increase(ds_api_response_count_total{code=\"4xx\"}[1m]))"
    },
    {
     "expr": "sum(increase(ds_api_response_count_total{code=\"5xx\"}[1m]))"
    }
   ]
  },
  {
   "title": "Api Resource Upload Size/5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(ds_api_resource_upload_size_bytes{}[5m])"
    }
   ]
  },
  {
   "title": "Api Resource Download Size/5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(ds_api_resource_download_size_bytes{}[5m])"
    }
   ]
  }
 ]
}